<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scores [
<!ELEMENT scores (student*)>
<!ELEMENT student (name,course,score)>
<!ATTLIST student id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ELEMENT score (#PCDATA)>
]>

<scores>
	<student id="1">
		<name>张三</name>
		<course>sql</course>
		<score>89</score>
	</student>

	<student id="2">
		<name>李宁</name>
		<course>sql</course>
		<score>90</score>
	</student>
   
	
</scores>